export interface MovieObject {
  adult: string,
  backdrop: string,
  id: number,
  media_type: string,
  original_language: string,
  original_title: string,
  overview: string,
  popularity: string,
  poster_path: string,
  release_date: string,
  title: string,
  video: string,
  vote_average: number,
  vote_count: number,
}
